### ISSUE TITLE
스타가 500개가 안되어도 PR 보낼 수 있나요? 

### ISSUE THREAD

**Issue by easylogic** [738/made-in-korea#1]
한국 프로젝트 중에 Star 개수가 500개가 안되도 PR보내도 될까요?

**Comment by 738** [comment]
@easylogic 기준을 100개로 내리는것으로 수정하겠습니다. 괜찮을까요??

**Comment by easylogic** [comment]
@738 

REAME.md 에 있는 다른 나라 프로젝트들을 같이 좀 봤는데. 
따로 스타의 기준은 없는 듯 해서 말씀 드려 보았어요. ^^ 

기준을 정하신거면  구조를 맞출려구여.

**Comment by easylogic** [comment]
> @easylogic 기준을 100개로 내리는것으로 수정하겠습니다. 괜찮을까요??

이것도 좋은 것 같습니다.

**Comment by 738** [comment]
@easylogic 

우선 스타수 기준 제거하는것으로 수정했습니다! 
스타수가 적은 좋은 프로젝트들도 많은것 같더라구요. 의견 감사드립니다.
